### ISSUE TITLE
可以告知网盘链接或者公众号链接吗

### ISSUE THREAD

**Issue by sherjy** [silencesmile/chinese_w2v_compare#1]

**Comment by silencesmile** [comment]
公众号：Python疯子
文章连接：https://mp.weixin.qq.com/s/y41McqBTWL5KERzjEeytaQ

**Comment by sherjy** [comment]
谢谢！ 另外想请问下载链接中“单独使用.zip”和"3个文件一起使用.zip"分别是什么？

**Comment by silencesmile** [comment]
单独使用：  里面是一个训练好的模型(1个文件)，使用时只用这一个模型文件就行  文件比较小
3个文件一起使用：里面是一个训练好的模型(这个模型由3个文件组成)，要使用这个模型，就得3个文件都包括，文件比较大，大约是单个模型的3-4倍

**Comment by sherjy** [comment]
好的，我再仔细看下，谢谢！
